# Site wide configuration

title: Outwith Studio
locale: en_US
description: Planning, Design, Spatial Strategy
logo: 
search: true
url: http://www.outwith.studio
# Jekyll configuration

permalink:   /:categories/:title/


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: J. McCartin
  email: mccartin@outwith.studio
